// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/menu.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	v1 "backend/api/v1"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMenuService is a mock of MenuService interface.
type MockMenuService struct {
	ctrl     *gomock.Controller
	recorder *MockMenuServiceMockRecorder
}

// MockMenuServiceMockRecorder is the mock recorder for MockMenuService.
type MockMenuServiceMockRecorder struct {
	mock *MockMenuService
}

// NewMockMenuService creates a new mock instance.
func NewMockMenuService(ctrl *gomock.Controller) *MockMenuService {
	mock := &MockMenuService{ctrl: ctrl}
	mock.recorder = &MockMenuServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuService) EXPECT() *MockMenuServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMenuService) Create(ctx context.Context, req *v1.MenuRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMenuServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMenuService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockMenuService) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMenuServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMenuService)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockMenuService) List(ctx context.Context, req *v1.MenuSearchRequest) (*v1.MenuSearchResponseData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*v1.MenuSearchResponseData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMenuServiceMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMenuService)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockMenuService) Update(ctx context.Context, id uint, req *v1.MenuRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMenuServiceMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMenuService)(nil).Update), ctx, id, req)
}
