// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/robot.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	v1 "backend/api/v1"
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRobotService is a mock of RobotService interface.
type MockRobotService struct {
	ctrl     *gomock.Controller
	recorder *MockRobotServiceMockRecorder
}

// MockRobotServiceMockRecorder is the mock recorder for MockRobotService.
type MockRobotServiceMockRecorder struct {
	mock *MockRobotService
}

// NewMockRobotService creates a new mock instance.
func NewMockRobotService(ctrl *gomock.Controller) *MockRobotService {
	mock := &MockRobotService{ctrl: ctrl}
	mock.recorder = &MockRobotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRobotService) EXPECT() *MockRobotServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRobotService) Create(ctx context.Context, req *v1.RobotRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRobotServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRobotService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockRobotService) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRobotServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRobotService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockRobotService) Get(ctx context.Context, id uint) (model.Robot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Robot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRobotServiceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRobotService)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockRobotService) List(ctx context.Context, req *v1.RobotSearchRequest) (*v1.RobotSearchResponseData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*v1.RobotSearchResponseData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRobotServiceMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRobotService)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockRobotService) Update(ctx context.Context, id uint, req *v1.RobotRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRobotServiceMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRobotService)(nil).Update), ctx, id, req)
}
