// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/api.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	v1 "backend/api/v1"
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApiRepository is a mock of ApiRepository interface.
type MockApiRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApiRepositoryMockRecorder
}

// MockApiRepositoryMockRecorder is the mock recorder for MockApiRepository.
type MockApiRepositoryMockRecorder struct {
	mock *MockApiRepository
}

// NewMockApiRepository creates a new mock instance.
func NewMockApiRepository(ctrl *gomock.Controller) *MockApiRepository {
	mock := &MockApiRepository{ctrl: ctrl}
	mock.recorder = &MockApiRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiRepository) EXPECT() *MockApiRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockApiRepository) Create(ctx context.Context, m *model.Api) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApiRepositoryMockRecorder) Create(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApiRepository)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockApiRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApiRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApiRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockApiRepository) Get(ctx context.Context, id uint) (model.Api, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Api)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApiRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApiRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockApiRepository) List(ctx context.Context, req *v1.ApiSearchRequest) ([]model.Api, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]model.Api)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockApiRepositoryMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApiRepository)(nil).List), ctx, req)
}

// ListAllGroups mocks base method.
func (m *MockApiRepository) ListAllGroups(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllGroups", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllGroups indicates an expected call of ListAllGroups.
func (mr *MockApiRepositoryMockRecorder) ListAllGroups(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllGroups", reflect.TypeOf((*MockApiRepository)(nil).ListAllGroups), ctx)
}

// Update mocks base method.
func (m *MockApiRepository) Update(ctx context.Context, id uint, data map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApiRepositoryMockRecorder) Update(ctx, id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApiRepository)(nil).Update), ctx, id, data)
}
