// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/avatar.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	v1 "backend/api/v1"
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAvatarStorage is a mock of AvatarStorage interface.
type MockAvatarStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarStorageMockRecorder
}

// MockAvatarStorageMockRecorder is the mock recorder for MockAvatarStorage.
type MockAvatarStorageMockRecorder struct {
	mock *MockAvatarStorage
}

// NewMockAvatarStorage creates a new mock instance.
func NewMockAvatarStorage(ctrl *gomock.Controller) *MockAvatarStorage {
	mock := &MockAvatarStorage{ctrl: ctrl}
	mock.recorder = &MockAvatarStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarStorage) EXPECT() *MockAvatarStorageMockRecorder {
	return m.recorder
}

// GetURL mocks base method.
func (m *MockAvatarStorage) GetURL(ctx context.Context, avatar string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, avatar)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockAvatarStorageMockRecorder) GetURL(ctx, avatar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockAvatarStorage)(nil).GetURL), ctx, avatar)
}

// SaveToLocal mocks base method.
func (m *MockAvatarStorage) SaveToLocal(ctx context.Context, req *v1.AvatarRequest, reader io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToLocal", ctx, req, reader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveToLocal indicates an expected call of SaveToLocal.
func (mr *MockAvatarStorageMockRecorder) SaveToLocal(ctx, req, reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToLocal", reflect.TypeOf((*MockAvatarStorage)(nil).SaveToLocal), ctx, req, reader)
}

// SaveToMinIO mocks base method.
func (m *MockAvatarStorage) SaveToMinIO(ctx context.Context, req *v1.AvatarRequest, reader io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToMinIO", ctx, req, reader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveToMinIO indicates an expected call of SaveToMinIO.
func (mr *MockAvatarStorageMockRecorder) SaveToMinIO(ctx, req, reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToMinIO", reflect.TypeOf((*MockAvatarStorage)(nil).SaveToMinIO), ctx, req, reader)
}
