// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/robot.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	v1 "backend/api/v1"
	model "backend/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRobotRepository is a mock of RobotRepository interface.
type MockRobotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRobotRepositoryMockRecorder
}

// MockRobotRepositoryMockRecorder is the mock recorder for MockRobotRepository.
type MockRobotRepositoryMockRecorder struct {
	mock *MockRobotRepository
}

// NewMockRobotRepository creates a new mock instance.
func NewMockRobotRepository(ctrl *gomock.Controller) *MockRobotRepository {
	mock := &MockRobotRepository{ctrl: ctrl}
	mock.recorder = &MockRobotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRobotRepository) EXPECT() *MockRobotRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRobotRepository) Create(ctx context.Context, v *model.Robot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRobotRepositoryMockRecorder) Create(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRobotRepository)(nil).Create), ctx, v)
}

// Delete mocks base method.
func (m *MockRobotRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRobotRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRobotRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockRobotRepository) Get(ctx context.Context, id uint) (model.Robot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Robot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRobotRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRobotRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockRobotRepository) List(ctx context.Context, req *v1.RobotSearchRequest) ([]model.Robot, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]model.Robot)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRobotRepositoryMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRobotRepository)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockRobotRepository) Update(ctx context.Context, id uint, data map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRobotRepositoryMockRecorder) Update(ctx, id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRobotRepository)(nil).Update), ctx, id, data)
}
