// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/token.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenStore is a mock of TokenStore interface.
type MockTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockTokenStoreMockRecorder
}

// MockTokenStoreMockRecorder is the mock recorder for MockTokenStore.
type MockTokenStoreMockRecorder struct {
	mock *MockTokenStore
}

// NewMockTokenStore creates a new mock instance.
func NewMockTokenStore(ctrl *gomock.Controller) *MockTokenStore {
	mock := &MockTokenStore{ctrl: ctrl}
	mock.recorder = &MockTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenStore) EXPECT() *MockTokenStoreMockRecorder {
	return m.recorder
}

// InvalidateRefreshToken mocks base method.
func (m *MockTokenStore) InvalidateRefreshToken(ctx context.Context, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateRefreshToken", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateRefreshToken indicates an expected call of InvalidateRefreshToken.
func (mr *MockTokenStoreMockRecorder) InvalidateRefreshToken(ctx, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateRefreshToken", reflect.TypeOf((*MockTokenStore)(nil).InvalidateRefreshToken), ctx, tokenID)
}

// InvalidateRefreshTokenByFamilyID mocks base method.
func (m *MockTokenStore) InvalidateRefreshTokenByFamilyID(ctx context.Context, familyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateRefreshTokenByFamilyID", ctx, familyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateRefreshTokenByFamilyID indicates an expected call of InvalidateRefreshTokenByFamilyID.
func (mr *MockTokenStoreMockRecorder) InvalidateRefreshTokenByFamilyID(ctx, familyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateRefreshTokenByFamilyID", reflect.TypeOf((*MockTokenStore)(nil).InvalidateRefreshTokenByFamilyID), ctx, familyID)
}

// InvalidateRefreshTokenByUserID mocks base method.
func (m *MockTokenStore) InvalidateRefreshTokenByUserID(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateRefreshTokenByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateRefreshTokenByUserID indicates an expected call of InvalidateRefreshTokenByUserID.
func (mr *MockTokenStoreMockRecorder) InvalidateRefreshTokenByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateRefreshTokenByUserID", reflect.TypeOf((*MockTokenStore)(nil).InvalidateRefreshTokenByUserID), ctx, userID)
}

// IsAccessTokenRevoked mocks base method.
func (m *MockTokenStore) IsAccessTokenRevoked(ctx context.Context, tokenID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAccessTokenRevoked", ctx, tokenID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAccessTokenRevoked indicates an expected call of IsAccessTokenRevoked.
func (mr *MockTokenStoreMockRecorder) IsAccessTokenRevoked(ctx, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAccessTokenRevoked", reflect.TypeOf((*MockTokenStore)(nil).IsAccessTokenRevoked), ctx, tokenID)
}

// IsRefreshTokenValid mocks base method.
func (m *MockTokenStore) IsRefreshTokenValid(ctx context.Context, tokenID, familyID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRefreshTokenValid", ctx, tokenID, familyID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRefreshTokenValid indicates an expected call of IsRefreshTokenValid.
func (mr *MockTokenStoreMockRecorder) IsRefreshTokenValid(ctx, tokenID, familyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRefreshTokenValid", reflect.TypeOf((*MockTokenStore)(nil).IsRefreshTokenValid), ctx, tokenID, familyID)
}

// RevokeAccessToken mocks base method.
func (m *MockTokenStore) RevokeAccessToken(ctx context.Context, tokenID string, expiry time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAccessToken", ctx, tokenID, expiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAccessToken indicates an expected call of RevokeAccessToken.
func (mr *MockTokenStoreMockRecorder) RevokeAccessToken(ctx, tokenID, expiry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAccessToken", reflect.TypeOf((*MockTokenStore)(nil).RevokeAccessToken), ctx, tokenID, expiry)
}

// StoreRefreshToken mocks base method.
func (m *MockTokenStore) StoreRefreshToken(ctx context.Context, tokenID, familyID string, userID uint, expiry time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshToken", ctx, tokenID, familyID, userID, expiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshToken indicates an expected call of StoreRefreshToken.
func (mr *MockTokenStoreMockRecorder) StoreRefreshToken(ctx, tokenID, familyID, userID, expiry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshToken", reflect.TypeOf((*MockTokenStore)(nil).StoreRefreshToken), ctx, tokenID, familyID, userID, expiry)
}
