// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/internal/handler"
	"backend/internal/job"
	"backend/internal/repository"
	"backend/internal/server"
	"backend/internal/service"
	"backend/pkg/app"
	"backend/pkg/email"
	"backend/pkg/jwt"
	"backend/pkg/log"
	"backend/pkg/server/http"
	"backend/pkg/sid"
	"backend/pkg/storage"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(viperViper, logger)
	syncedEnforcer := repository.NewCasbinEnforcer(viperViper, logger, db)
	cache := repository.NewCache()
	universalClient := repository.NewRedis(viperViper, logger)
	repositoryRepository := repository.NewRepository(db, syncedEnforcer, cache, universalClient, logger)
	tokenStore := repository.NewTokenStore(repositoryRepository)
	jwtJWT := jwt.NewJwt(viperViper, tokenStore)
	handlerHandler := handler.NewHandler(logger)
	sidSid := sid.NewSid()
	emailEmail := email.NewEmail(viperViper)
	storageStorage := storage.NewStorage(viperViper)
	transaction := repository.NewTransaction(repositoryRepository)
	serviceService := service.NewService(logger, sidSid, jwtJWT, emailEmail, storageStorage, transaction)
	userRepository := repository.NewUserRepository(repositoryRepository)
	roleRepository := repository.NewRoleRepository(repositoryRepository)
	menuRepository := repository.NewMenuRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository, roleRepository, menuRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	roleService := service.NewRoleService(serviceService, roleRepository)
	roleHandler := handler.NewRoleHandler(handlerHandler, roleService)
	menuService := service.NewMenuService(serviceService, menuRepository)
	menuHandler := handler.NewMenuHandler(handlerHandler, menuService)
	apiRepository := repository.NewApiRepository(repositoryRepository)
	apiService := service.NewApiService(serviceService, apiRepository)
	apiHandler := handler.NewApiHandler(handlerHandler, apiService)
	robotRepository := repository.NewRobotRepository(repositoryRepository)
	robotService := service.NewRobotService(serviceService, robotRepository)
	robotHandler := handler.NewRobotHandler(handlerHandler, robotService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, syncedEnforcer, userHandler, roleHandler, menuHandler, apiHandler, robotHandler)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewCache, repository.NewRepository, repository.NewTransaction, repository.NewTokenStore, repository.NewCasbinEnforcer, repository.NewUserRepository, repository.NewRoleRepository, repository.NewMenuRepository, repository.NewApiRepository, repository.NewRobotRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewRoleService, service.NewMenuService, service.NewApiService, service.NewRobotService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewMenuHandler, handler.NewApiHandler, handler.NewRobotHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
