// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/internal/handler"
	"backend/internal/job"
	"backend/internal/repository"
	"backend/internal/server"
	"backend/internal/service"
	"backend/pkg/app"
	"backend/pkg/jwt"
	"backend/pkg/log"
	"backend/pkg/server/http"
	"backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	db := repository.NewDB(viperViper, logger)
	syncedEnforcer := repository.NewCasbinEnforcer(viperViper, logger, db)
	handlerHandler := handler.NewHandler(logger)
	repositoryRepository := repository.NewRepository(logger, db, syncedEnforcer)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	menuRepository := repository.NewMenuRepository(repositoryRepository)
	roleRepository := repository.NewRoleRepository(repositoryRepository)
	apiRepository := repository.NewApiRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository, menuRepository, roleRepository, apiRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	robotRepository := repository.NewRobotRepository(repositoryRepository)
	robotService := service.NewRobotService(serviceService, robotRepository)
	robotHandler := handler.NewRobotHandler(handlerHandler, robotService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, syncedEnforcer, userHandler, robotHandler)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewRoleRepository, repository.NewApiRepository, repository.NewMenuRepository, repository.NewCasbinEnforcer, repository.NewRobotRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewRobotService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewRobotHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
