apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: robotshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "ChangeMe123!"
        - name: MYSQL_DATABASE
          value: "robotshop"
        - name: MYSQL_USER
          value: "robotshop"
        - name: MYSQL_PASSWORD
          value: "ChangeMe123!"
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-pChangeMe123!"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
      - name: mysql-config
        configMap:
          name: mysql-config
      - name: mysql-init
        configMap:
          name: mysql-init