apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: robotshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis:7
        env:
        - name: TZ
          value: "Asia/Shanghai"
        command: ["redis-server"]
        args: ["/usr/local/etc/redis/redis.conf", "--requirepass", "ChangeMe123!"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        livenessProbe:
          exec:
            command: ["redis-cli", "-a", "ChangeMe123!", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc
      - name: redis-config
        configMap:
          name: redis-config